# Author: Chiara Zefferer, Dominik Bregovic
# Last Changes: 22.01.2023
#

name: Java CI with Maven

on:
  pull_request:
    branches: [ "pullrequest" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3 #Chaching dependencies to speed up workflow
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven

      #Build and Compile
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Move artifacts
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging